# Generated by Django 3.1 on 2022-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('edition', 'edition'), ('platform', 'platform')], max_length=100),
        ),
    ]
